=== claudioborgogno/PhoneGap-Enterprise-Code-Bundle/raml/schemas/person.json
{
	"type": "object",
	"$schema": "http://json-schema.org/draft-03/schema",
	"id": "http://jsonschema.net",
	"required": true,
	"properties": {
		"personId": {
			"type": "integer",
			"required": false
		},
		"userId": {
			"type": "string",
			"required": true,
			"maxLength": 32
		},
		"firstName": {
			"type": "string",
			"required": true,
			"maxLength": 255
		},
		"middleName": {
			"type": "string",
			"required": false,
			"maxLength": 255
		},
		"lastName": {
			"type": "string",
			"required": false,
			"maxLength": 255
		},
		"administratorId": {
			"type": "integer",
			"required": false
		},
		"changeDate": {
			"type": "date",
			"required": true
		},
		"changeUser": {
			"type": "string",
			"required": true,
			"maxLength": 32
		}
	}
}

=== claudioborgogno/PhoneGap-Enterprise-Code-Bundle/raml/examples/personExampleCollection.json
[
	{ "personId" : 1,
		"userId" : "jdoe",
		"firstName" : "John",
		"lastName" : "Doe",
		"changeDate" : "Sun, 06 Nov 1994 08:49:37 GMT",
		"changeUser" : "SYSADMIN"
	},
	{ "personId" : 2,
		"userId": "bsmith",
		"firstName" : "Bob",
		"middleName" : "A",
		"lastName" : "Smith",
		"administratorId" : 1,
		"changeDate": "Sun, 06 Nov 1994 08:49:37 GMT",
		"changeUser" : "SYSADMIN"
	}
]
